### ISSUE TITLE
Changing css class for draggable items

### ISSUE THREAD

**Issue by knownasilya** [IvyApp/ivy-sortable#1]
Would be nice if there was an attribute, like `itemClass`.

**Comment by omghax** [comment]
I actually do this in the demo app here: https://github.com/IvyApp/ivy-sortable/blob/master/tests/dummy/app/templates/index.hbs#L7-L9

Since `ivy-sortable` is just a wrapper around Ember's built-in `collection` helper, you can use `itemClassNames` to set classes on the list items. Any property prefixed with `item` will be passed along to the child views (see http://emberjs.com/api/classes/Ember.Handlebars.helpers.html#toc_forwarded-code-item-code-named-options).
