### ISSUE TITLE
Broken with Ember 1.10.0

### ISSUE THREAD

**Issue by justinph** [IvyApp/ivy-sortable#4]
This package does not work with ember 1.10.0. It hangs on [line 20 in /addon/helpers/ivy-sortable.js](https://github.com/IvyApp/ivy-sortable/blob/master/addon/helpers/ivy-sortable.js#L20):
`return Ember.Handlebars.helpers.collection.call(ctx, 'ivy-sortable', options);`

It seems this has to do with the new use of HTMLBars. I am not quite familiar enough (yet) with the internals of ivy sortable and how it works with the CollectionView to fix it. From what I can tell,  the colleciton helper needs to be called similar to this, now:

`return Ember.Handlebars.helpers.collection.helperFunction( ['ivy-sortable'], options.hash, options, {data:options.data});`

But, not quite like that because it doesn't work. I'm not exactly sure how to give `Ember.Handlebars.helpers.collection.helperFunction` the data.view it is looking for. It seems that this is the wrong view that is being passed in.

**Comment by omghax** [comment]
Yep, due to some changes HTMLBars introduced, namely making the `registerHelper` function private, there's no officially supported way for me to register a helper like `ivy-sortable`. Fortunately the helper is just a thin wrapper around `{{collection}}`, which still works in Ember 1.10.

So the following:

``` handlebars
{{#ivy-sortable things}}
  ...
{{/ivy-sortable}}
```

should be changed to:

``` handlebars
{{#collection "ivy-sortable" content=things}}
  ...
{{/collection}}
```

Since the helper is relying on a (now private) API, I've decided to deprecate it in the latest beta release, 1.0.0-beta.3. Ideally at some point I'd like to change `ivy-sortable` from a CollectionView to a component, but I'm not sure if that's possible yet.

Does that work for you? I'm closing the issue for now, but feel free to comment if there's something about your use case I've missed. Thanks!
